name: Add issues to project board

on:
  issues:
    types: [opened, reopened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/tommyroar/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
